import { Bell, Bot, Database, Globe, Lock, type LucideIcon } from 'lucide-react';
import { getAdminCredentialHint } from '@/lib/admin-auth';
import type { AdminSecurityState, AdminSettingsCopy, AdminSettingsState, AdminSettingsTabId } from './types';

export const DEFAULT_ADMIN_CREDENTIAL = getAdminCredentialHint();

export const DEFAULT_ADMIN_SETTINGS: AdminSettingsState = {
    siteName: 'VOXO Cinematic Magazine',
    siteDescription: 'Premium Curated Music Experience',
    contactEmail: 'hello@voxo.edit',
    geminiApiKey: '',
    globalPlaylist: '',
    maintenanceMode: false,
    maintenanceTitle: '점검 진행 중',
    maintenanceMessage: '현재 사이트 점검을 진행하고 있습니다. 더 안정적인 서비스와 콘텐츠 경험을 위해 잠시 공개 화면을 닫아두었습니다. 작업이 끝나면 다시 정상적으로 접속하실 수 있습니다.',
    maintenanceEta: '',
    maintenanceNoticeUrl: '',
    aiPromptResearch: 'Research the artist "{artistName}" and the song "{songTitle}". Return concise factual bullet points only.',
    aiPromptWrite: 'Write the article in {language} using {facts}. Follow this direction: {concept}. Use category context {categoryName}. Start with "Title:" and "Intro:".',
    aiPromptSeo: 'Create comma-separated SEO tags from {articleText}. Prefer existing tags from {existingTags}.',
    aiPromptConcept: 'Focus on mood, production detail, and why the song matters.',
};

export const DEFAULT_ADMIN_SECURITY: AdminSecurityState = {
    adminEmail: DEFAULT_ADMIN_CREDENTIAL.email,
    newPassword: '',
    confirmPassword: '',
};

export const adminSettingKeys = {
    siteName: 'site_name',
    siteDescription: 'site_description',
    contactEmail: 'contact_email',
    geminiApiKey: 'gemini_api_key',
    globalPlaylist: 'global_spotify_playlist',
    maintenanceMode: 'maintenance_mode',
    maintenanceTitle: 'maintenance_title',
    maintenanceMessage: 'maintenance_message',
    maintenanceEta: 'maintenance_eta',
    maintenanceNoticeUrl: 'maintenance_notice_url',
    aiPromptResearch: 'ai_prompt_research',
    aiPromptWrite: 'ai_prompt_write',
    aiPromptSeo: 'ai_prompt_seo',
    aiPromptConcept: 'ai_prompt_concept',
    adminEmail: 'admin_login_email',
} as const;

export const adminSettingLoadOrder = [
    adminSettingKeys.siteName,
    adminSettingKeys.siteDescription,
    adminSettingKeys.contactEmail,
    adminSettingKeys.geminiApiKey,
    adminSettingKeys.globalPlaylist,
    adminSettingKeys.maintenanceMode,
    adminSettingKeys.maintenanceTitle,
    adminSettingKeys.maintenanceMessage,
    adminSettingKeys.maintenanceEta,
    adminSettingKeys.maintenanceNoticeUrl,
    adminSettingKeys.aiPromptResearch,
    adminSettingKeys.aiPromptWrite,
    adminSettingKeys.aiPromptSeo,
    adminSettingKeys.aiPromptConcept,
    adminSettingKeys.adminEmail,
] as const;

export const adminSettingsTabs: Array<{ id: AdminSettingsTabId; icon: LucideIcon }> = [
    { id: 'general', icon: Globe },
    { id: 'ai', icon: Bot },
    { id: 'integrations', icon: Database },
    { id: 'security', icon: Lock },
    { id: 'notifications', icon: Bell },
];

export const adminSettingsCopy: Record<'en' | 'ko', AdminSettingsCopy> = {
    en: {
        title: 'Platform Settings',
        subtitle: 'Manage site identity, AI prompts, maintenance mode, and admin access in one place.',
        save: 'Save Settings',
        saving: 'Saving...',
        saved: 'Settings saved successfully.',
        failed: 'Failed to save some settings.',
        loading: 'Loading settings...',
        tabs: {
            general: 'General',
            ai: 'AI Agents',
            integrations: 'Integrations',
            security: 'Security',
            notifications: 'Notifications',
        },
        general: {
            section: 'Site Identity',
            siteName: 'Site Name',
            siteDescription: 'Site Description',
            contactEmail: 'Contact Email',
            adminLanguage: 'Admin Language',
            languageHelp: 'Choose the language used inside the admin interface.',
            koreanLabel: 'Korean',
            englishLabel: 'English',
        },
        ai: {
            section: 'AI Prompt Settings',
            description: 'These templates are used by the AI draft generation pipeline.',
            concept: 'Default Editorial Direction',
            research: 'Research Prompt',
            write: 'Writing Prompt',
            seo: 'SEO Prompt',
        },
        integrations: {
            section: 'External Integrations',
            spotify: 'Spotify credentials are managed via environment variables.',
            gemini: 'Google Gemini API Key',
            playlist: 'Global Spotify Playlist URL',
        },
        security: {
            section: 'Admin Access',
            description: 'Change the default admin login used for the built-in management access.',
            adminEmail: 'Admin Login Email',
            newPassword: 'New Password',
            confirmPassword: 'Confirm Password',
            saveAccess: 'Update Admin Login',
            savingAccess: 'Updating...',
            savedAccess: 'Admin login updated successfully.',
            passwordHelp: 'Use at least 8 characters. This replaces the built-in default admin login.',
            mismatch: 'Password confirmation does not match.',
            maintenance: 'Maintenance Mode',
            maintenanceHelp: 'When enabled, public visitors are redirected to the maintenance page while admin access stays available.',
            maintenanceTitle: 'Maintenance Title',
            maintenanceMessage: 'Maintenance Message',
            maintenanceEta: 'Expected Recovery Time',
            maintenanceNoticeUrl: 'Notice Link URL',
            fallbackTitle: 'Current quick access',
            fallbackText: 'If you have not changed the admin login yet, the current starter account is shown below.',
            fallbackId: 'ID',
            fallbackPassword: 'PW',
        },
        notifications: {
            section: 'Notifications',
            placeholder: 'Notification routing is not connected yet.',
        },
    },
    ko: {
        title: '관리자 설정',
        subtitle: '사이트 기본 정보, AI 프롬프트, 점검 모드, 관리자 계정을 한곳에서 관리합니다.',
        save: '설정 저장',
        saving: '저장 중...',
        saved: '설정이 저장되었습니다.',
        failed: '일부 설정 저장에 실패했습니다.',
        loading: '설정을 불러오는 중...',
        tabs: {
            general: '일반',
            ai: 'AI 설정',
            integrations: '연동',
            security: '보안',
            notifications: '알림',
        },
        general: {
            section: '사이트 기본 정보',
            siteName: '사이트 이름',
            siteDescription: '사이트 설명',
            contactEmail: '문의 이메일',
            adminLanguage: '관리자 언어',
            languageHelp: '관리자 화면에서 사용할 언어를 선택합니다.',
            koreanLabel: '한국어',
            englishLabel: '영어',
        },
        ai: {
            section: 'AI 프롬프트 설정',
            description: 'AI 초안 생성 흐름에서 사용하는 기본 템플릿입니다.',
            concept: '기본 작성 방향',
            research: '리서치 프롬프트',
            write: '본문 작성 프롬프트',
            seo: 'SEO 태그 프롬프트',
        },
        integrations: {
            section: '외부 연동',
            spotify: 'Spotify 인증 정보는 환경변수로 관리됩니다.',
            gemini: 'Google Gemini API Key',
            playlist: '전역 Spotify 플레이리스트 URL',
        },
        security: {
            section: '관리자 접근 계정',
            description: '기본 관리자 로그인 계정을 관리자 화면에서 직접 변경할 수 있습니다.',
            adminEmail: '관리자 로그인 이메일',
            newPassword: '새 비밀번호',
            confirmPassword: '새 비밀번호 확인',
            saveAccess: '관리자 로그인 변경',
            savingAccess: '변경 중...',
            savedAccess: '관리자 로그인 정보가 저장되었습니다.',
            passwordHelp: '8자 이상으로 입력해 주세요. 저장하면 기본 관리자 로그인 정보가 바로 교체됩니다.',
            mismatch: '비밀번호 확인 값이 일치하지 않습니다.',
            maintenance: '점검 모드',
            maintenanceHelp: '활성화하면 방문자는 점검 페이지로 이동하고, 관리자 화면은 계속 사용할 수 있습니다.',
            maintenanceTitle: '점검 안내 제목',
            maintenanceMessage: '점검 안내 문구',
            maintenanceEta: '예상 복구 시간',
            maintenanceNoticeUrl: '공지 링크 URL',
            fallbackTitle: '현재 빠른 접속 정보',
            fallbackText: '아직 관리자 로그인을 변경하지 않았다면 아래 기본 계정으로 바로 접속할 수 있습니다.',
            fallbackId: 'ID',
            fallbackPassword: 'PW',
        },
        notifications: {
            section: '알림',
            placeholder: '알림 라우팅 기능은 아직 연결되지 않았습니다.',
        },
    },
};
