import type { AIPromptManagerCopy } from './types';

export const AI_PROMPT_VARIABLES = [
    '{artistName}',
    '{songTitle}',
    '{facts}',
    '{concept}',
    '{categoryName}',
    '{categoryPromptBlock}',
    '{curationPromptBlock}',
    '{draftText}',
    '{articleWordRange}',
] as const;

export const aiPromptManagerCopy: Record<'en' | 'ko', AIPromptManagerCopy> = {
    en: {
        title: 'AI Prompt Manager',
        subtitle:
            'Edit your AI writing system in one place. Base templates, category rules, curation profiles, and length presets are all organized into focused editor tabs.',
        save: 'Save Prompt Rules',
        saving: 'Saving...',
        reset: 'Revert Changes',
        resettingHint: 'No unsaved changes',
        saved: 'AI prompt settings saved successfully.',
        failed: 'Failed to save AI prompt settings.',
        loading: 'Loading AI prompt settings...',
        variablesTitle: 'Available Variables',
        variablesDescription:
            'Click a token to copy it. These variables can be inserted into the global prompt templates.',
        copyVariable: 'Copy variable',
        copyAllVariables: 'Copy all variables',
        copied: 'Copied to clipboard.',
        usageTipsTitle: 'Usage Tips',
        usageTips: [
            'Keep the core instruction stable, and move category-specific guidance into the category tab.',
            'Use the curation profile tab for tone and writing posture, not factual research instructions.',
            'If drafts become too short, review both the write template and the selected length guidance together.',
        ],
        promptSectionLabel: 'Templates',
        templateFlowHint: 'Organized in the actual draft generation order.',
        categorySectionLabel: 'Category Rules',
        curationSectionLabel: 'Curation Profiles',
        lengthSectionLabel: 'Length Rules',
        previewSectionLabel: 'Preview',
        basicInfoGroup: 'Basic Information',
        rulesGroup: 'Rules',
        framingGroup: 'Title, Intro, Opening, Ending',
        identityGroup: 'Profile Identity',
        writingGroup: 'Writing Rules',
        styleGroup: 'Style Guide',
        compactSummary: 'Current Applied Rule Summary',
        currentCategory: 'Category',
        currentProfile: 'Curation Profile',
        currentLength: 'Length Preset',
        copyFullPrompt: 'Copy Full Prompt',
        copiedFullPrompt: 'Full prompt copied.',
        expand: 'Expand',
        collapse: 'Collapse',
        addItem: 'Add item',
        emptyList: 'No items yet. Add the first rule.',
        moveUp: 'Move up',
        moveDown: 'Move down',
        remove: 'Remove',
        unsavedDotLabel: 'Unsaved changes',
        templates: {
            concept: 'Default Editorial Direction',
            conceptDescription:
                'This is the global creative direction used when no custom concept is typed in the AI desk.',
            research: 'Research Prompt',
            researchDescription:
                'Controls what factual notes the AI gathers before writing the article.',
            write: 'Writing Prompt',
            writeDescription:
                'The main article-generation template. This is the most important prompt in the pipeline.',
            refine: 'Refinement Prompt',
            refineDescription:
                'Used after the first draft to tighten the structure, intro, title, and overall flow.',
            seo: 'SEO Prompt',
            seoDescription:
                'Used for support metadata and SEO-style tag generation after the body is produced.',
            variablesHelper: 'Available variables',
        },
        fields: {
            selectCategory: 'Category to edit',
            selectProfile: 'Curation profile to edit',
            selectLength: 'Length preset to edit',
            displayName: 'Display Name',
            label: 'Editorial Label',
            summary: 'Summary',
            editorialGoal: 'Editorial Goal',
            toneDirectives: 'Tone Rules',
            structureDirectives: 'Structure Rules',
            middleParagraphMoves: 'Paragraph Flow',
            titleDirective: 'Title Rule',
            heroExcerptDirective: 'Hero Excerpt Rule',
            openingDirective: 'Opening Rule',
            endingDirective: 'Ending Rule',
            shortDescription: 'Short Description',
            longDescription: 'Long Description',
            readerPromise: 'Reader Promise',
            defaultConcept: 'Default Concept',
            requiredSections: 'Required Sections',
            writingDirectives: 'Writing Directives',
            preferredPhrases: 'Preferred Phrases',
            avoidPhrases: 'Avoid Phrases',
            styleExamples: 'Style Examples',
            wordRangeLabel: 'Word Range',
            guidance: 'Guidance',
            onePerLine: 'Repeatable list field',
        },
        previews: {
            categoryBlock: 'Category Block Preview',
            curationBlock: 'Curation Block Preview',
            writePrompt: 'Writing Prompt Preview',
            refinePrompt: 'Refinement Prompt Preview',
        },
        tabs: {
            basic: {
                id: 'basic',
                label: 'Basic Settings',
                description:
                    'Review the global guidance, supported variables, and common usage tips before editing the prompt system.',
            },
            templates: {
                id: 'templates',
                label: 'Base Templates',
                description:
                    'Edit the global prompt templates used across research, writing, refinement, and SEO support.',
            },
            category: {
                id: 'category',
                label: 'Category Rules',
                description:
                    'Tune how each category shapes the title, intro, paragraph movement, opening, and ending.',
            },
            curation: {
                id: 'curation',
                label: 'Curation Profiles',
                description:
                    'Adjust the editorial mode, reader promise, required sections, and writing posture for each profile.',
            },
            length: {
                id: 'length',
                label: 'Length Rules',
                description:
                    'Control target word range and guidance for each article volume preset.',
            },
            preview: {
                id: 'preview',
                label: 'Preview',
                description:
                    'Review the currently selected category, profile, and length combination before saving or testing.',
            },
        },
    },
    ko: {
        title: 'AI 프롬프트 관리자',
        subtitle:
            'AI 글쓰기 기본 템플릿과 카테고리, 큐레이션 프로필, 글자 수별 규칙을 한 곳에서 수정할 수 있습니다.',
        save: '프롬프트 저장',
        saving: '저장 중...',
        reset: '변경 되돌리기',
        resettingHint: '저장 전 변경사항 없음',
        saved: 'AI 프롬프트 설정이 저장되었습니다.',
        failed: 'AI 프롬프트 설정 저장에 실패했습니다.',
        loading: 'AI 프롬프트 설정을 불러오는 중입니다...',
        variablesTitle: '사용 가능한 변수',
        variablesDescription:
            '토큰을 누르면 바로 복사됩니다. 이 변수들은 기본 템플릿 안에서 사용할 수 있습니다.',
        copyVariable: '변수 복사',
        copyAllVariables: '전체 변수 복사',
        copied: '클립보드에 복사되었습니다.',
        usageTipsTitle: '사용 팁',
        usageTips: [
            '공통 지시는 기본 템플릿에 두고, 카테고리별 차이는 카테고리 규칙 탭에서 관리하는 편이 안정적입니다.',
            '큐레이션 프로필 탭에는 글의 태도와 문체 방향을 넣고, 사실 리서치 지시는 리서치 프롬프트에 두는 것이 좋습니다.',
            '초안이 너무 짧게 나오면 본문 작성 프롬프트와 분량 규칙을 함께 확인해 보세요.',
        ],
        promptSectionLabel: '기본 템플릿',
        templateFlowHint: '실제 글 생성 순서에 맞춰 정렬되어 있습니다.',
        categorySectionLabel: '카테고리 규칙',
        curationSectionLabel: '큐레이션 프로필',
        lengthSectionLabel: '분량 규칙',
        previewSectionLabel: '미리보기',
        basicInfoGroup: '기본 정보',
        rulesGroup: '중간 규칙',
        framingGroup: '제목 및 도입·마무리 규칙',
        identityGroup: '프로필 기본 정보',
        writingGroup: '작성 규칙',
        styleGroup: '문체 가이드',
        compactSummary: '현재 적용 규칙 요약',
        currentCategory: '카테고리',
        currentProfile: '큐레이션 프로필',
        currentLength: '분량 규칙',
        copyFullPrompt: '전체 프롬프트 복사',
        copiedFullPrompt: '전체 프롬프트를 복사했습니다.',
        expand: '펼치기',
        collapse: '접기',
        addItem: '항목 추가',
        emptyList: '아직 항목이 없습니다. 첫 항목을 추가해 주세요.',
        moveUp: '위로 이동',
        moveDown: '아래로 이동',
        remove: '삭제',
        unsavedDotLabel: '저장되지 않은 변경사항',
        templates: {
            concept: '기본 작성 방향',
            conceptDescription:
                'AI 데스크에서 별도 컨셉을 입력하지 않았을 때 기본으로 쓰이는 전역 작성 방향입니다.',
            research: '리서치 프롬프트',
            researchDescription:
                '본문 작성 전에 어떤 사실 정보를 조사할지 결정하는 프롬프트입니다.',
            write: '본문 작성 프롬프트',
            writeDescription:
                '실제 기사 본문을 만드는 핵심 프롬프트입니다. 가장 중요하게 다뤄야 하는 영역입니다.',
            refine: '다듬기 프롬프트',
            refineDescription:
                '1차 초안 이후 제목, 인트로, 구조, 문단 흐름을 정리할 때 사용하는 프롬프트입니다.',
            seo: 'SEO 프롬프트',
            seoDescription:
                '본문 작성 이후 SEO용 보조 텍스트와 태그 생성을 다룰 때 사용하는 프롬프트입니다.',
            variablesHelper: '사용 가능 변수',
        },
        fields: {
            selectCategory: '수정할 카테고리',
            selectProfile: '수정할 큐레이션 프로필',
            selectLength: '수정할 분량 옵션',
            displayName: '표시 이름',
            label: '편집 모드 이름',
            summary: '요약',
            editorialGoal: '편집 목표',
            toneDirectives: '톤 규칙',
            structureDirectives: '구조 규칙',
            middleParagraphMoves: '문단 전개',
            titleDirective: '제목 규칙',
            heroExcerptDirective: '히어로 문구 규칙',
            openingDirective: '도입 규칙',
            endingDirective: '마무리 규칙',
            shortDescription: '짧은 설명',
            longDescription: '긴 설명',
            readerPromise: '독자 약속',
            defaultConcept: '기본 컨셉',
            requiredSections: '필수 섹션',
            writingDirectives: '작성 지시',
            preferredPhrases: '선호 문구',
            avoidPhrases: '피할 문구',
            styleExamples: '스타일 예시',
            wordRangeLabel: '분량 범위',
            guidance: '가이드',
            onePerLine: '반복형 목록 필드',
        },
        previews: {
            categoryBlock: '카테고리 블록 미리보기',
            curationBlock: '큐레이션 블록 미리보기',
            writePrompt: '본문 프롬프트 미리보기',
            refinePrompt: '다듬기 프롬프트 미리보기',
        },
        tabs: {
            basic: {
                id: 'basic',
                label: '기본 설정',
                description:
                    '전역 안내, 사용 가능한 변수, 공통 사용 팁을 확인하는 탭입니다. 프롬프트를 본격 수정하기 전에 구조를 빠르게 파악할 수 있습니다.',
            },
            templates: {
                id: 'templates',
                label: '기본 템플릿',
                description:
                    '리서치, 본문 작성, 다듬기, SEO까지 전역으로 사용하는 기본 프롬프트를 편집합니다.',
            },
            category: {
                id: 'category',
                label: '카테고리 규칙',
                description:
                    '카테고리마다 제목, 인트로, 문단 흐름, 도입, 마무리 규칙이 어떻게 달라지는지 설정합니다.',
            },
            curation: {
                id: 'curation',
                label: '큐레이션 프로필',
                description:
                    '큐레이션 프로필별 글의 태도, 독자 약속, 필수 섹션, 선호 문구를 조정합니다.',
            },
            length: {
                id: 'length',
                label: '분량 규칙',
                description:
                    '분량 옵션별 목표 글자 수 범위와 작성 가이드를 빠르게 수정합니다.',
            },
            preview: {
                id: 'preview',
                label: '미리보기',
                description:
                    '현재 선택된 카테고리, 프로필, 분량 규칙이 실제 프롬프트에 어떻게 합쳐지는지 최종 검토합니다.',
            },
        },
    },
};
